RunAction "01_Login", oneIteration
RunAction "02_Launch_TCode_va01", oneIteration
RunAction "03_va01_create_sales_document", oneIteration
RunAction "04_va01_order_header", oneIteration
RunAction "05_va01_order_details", oneIteration
RunAction "06_va01_create_new_order", oneIteration
RunAction "07_va01_exit", oneIteration
RunAction "08_Launch_TCode_vl01n", oneIteration
RunAction "09_vl01n_create_outbound_delivery_with_order_reference", oneIteration
RunAction "10_vl01n_outbound_delivery_create_overview", oneIteration
RunAction "11_vl01n_exit", oneIteration
RunAction "12_Launch_TCode_vl02n", oneIteration
RunAction "13_change_outbound_delivery", oneIteration
RunAction "14_change_outbound_delivery_details", oneIteration
RunAction "15_Launch_TCode_vf01", oneIteration
RunAction "16_vf01_create_billing_document", oneIteration
RunAction "17_Nav_to_Post_Incoming_Payments", oneIteration
RunAction "18_Post_Incoming_Payments", oneIteration
RunAction "99_logout", oneIteration
