RunAction "AOS_Special_Offer", oneIteration
RunAction "AOS_Update_Product_Details", oneIteration
RunAction "AOS_Our_Products", oneIteration
RunAction "AOS_Add_to_Cart", oneIteration
RunAction "AOS_View_Cart", oneIteration
RunAction "AOS_Clear_Cart", oneIteration
RunAction "AOS_Checkout", oneIteration
RunAction "AOS_Login_Existing_User", oneIteration
RunAction "AOS_Login_Register_New_User", oneIteration
RunAction "AOS_Login_FB_User", oneIteration
RunAction "AOS_Edit_Shipping_Details", oneIteration
RunAction "AOS_SafePay_Payment", oneIteration
RunAction "AOS_MasterCredit_Payment", oneIteration
RunAction "AOS_Logout", oneIteration
RunAction "AOS_Follow_Us_FB", oneIteration
RunAction "AOS_Follow_Us_X", oneIteration
RunAction "AOS_Follow_Us_LI", oneIteration
RunAction "AOS_Contact_Us_Message", oneIteration
RunAction "AOS_Contact_Us_Chat", oneIteration
RunAction "AOS_Popular_Items", oneIteration
RunAction "AOS_Help_About", oneIteration
RunAction "AOS_Help_AOS_Versions", oneIteration
RunAction "AOS_Help_Management_Console", oneIteration
RunAction "AOS_Search", oneIteration
